/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerForm.java
 *
 * Created on 23-feb-2012, 13:03:15
 */
package es.jimenezfrontend.gui;

import es.jimenezfrontend.objects.Game;
import java.awt.Component;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.TitledBorder;

/**
 *
 * @author rocio
 */
public class IAForm extends javax.swing.JFrame {

    Component[] components;
    int card_number = 0;
    String thepath = "/es/jimenezfrontend/images/";
    URL url;
    Game myGame = Game.getInstance();
    double value = 0.0;
    int pnumber;
    boolean stop_game = false;
    boolean is_paused = false;

    public IAForm(String name, int player_number) {

	initComponents();
	pnumber = player_number;
	final TitledBorder tb = BorderFactory.createTitledBorder(name);
	player_panel.setBorder(tb);
	player_panel.repaint();
	stop_game = false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        player_panel = new javax.swing.JPanel();
        carta1j = new javax.swing.JLabel();
        carta2j = new javax.swing.JLabel();
        carta3j = new javax.swing.JLabel();
        carta4j = new javax.swing.JLabel();
        carta5j = new javax.swing.JLabel();
        carta6j = new javax.swing.JLabel();
        carta7j = new javax.swing.JLabel();
        carta8j = new javax.swing.JLabel();
        carta9j = new javax.swing.JLabel();
        carta10j = new javax.swing.JLabel();
        resulttext = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        player_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 1"));
        player_panel.setLayout(new java.awt.GridLayout(1, 0));
        player_panel.add(carta1j);
        player_panel.add(carta2j);
        player_panel.add(carta3j);
        player_panel.add(carta4j);
        player_panel.add(carta5j);
        player_panel.add(carta6j);
        player_panel.add(carta7j);
        player_panel.add(carta8j);
        player_panel.add(carta9j);
        player_panel.add(carta10j);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(player_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(resulttext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(player_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(resulttext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:

    try {
	components = this.player_panel.getComponents();

    }
    catch (Exception e) {
	System.out.println(e.toString());
    }


}//GEN-LAST:event_formWindowOpened

    public void get_card() {

	String[] response = myGame.IADeal();
	//System.out.println(thepath + response[0]);
	value = value + Double.valueOf(response[1]);
	System.out.println(value);
	url = this.getClass().getResource(thepath + response[0]);
	ImageIcon icon = new ImageIcon(url);
	((JLabel) components[card_number]).setIcon(icon);
	((JLabel) components[card_number]).setVisible(true);
	card_number++;
	StopGame();
	myGame.PauseIA(pnumber);
	if (stop_game == true) {
	    stick();
	}
	else {
	    if (Boolean.valueOf(response[2])) {
		myGame.MakeIADeal();
	    }
	}
    }

    public void pausing() {
	int total = 0;
	synchronized (this) {
	    for (int i = 0; i < 10000; i++) {
		total += i;
		System.out.println("IA Pensando..." + total);
	    }
	    notify();
	}
    }

    private void StopGame() {
	int probability = 0 + (int) (Math.random() * ((100 - 0) + 1));
	//System.out.println("probabilidad" + probability);
	if (value < 1){
	    stop_game = false;
	}
	else if (value < 4 && probability > 20) {
	    stop_game = true;
	}
	else if( value > 4 && value < 6 && probability > 50) {
	    stop_game = true;
	}
	else if (value > 5.9  && value < 7.1 && probability > 90) {
	    stop_game = true;
	}
	if (value >= 7.5) {
	    stop_game = true;
	}
	//System.out.println("parar " + stop_game);
    }

    private void stick() {
	String[] response2 = myGame.stopThread(pnumber, value);
	resulttext.setText(response2[0]);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carta10j;
    private javax.swing.JLabel carta1j;
    private javax.swing.JLabel carta2j;
    private javax.swing.JLabel carta3j;
    private javax.swing.JLabel carta4j;
    private javax.swing.JLabel carta5j;
    private javax.swing.JLabel carta6j;
    private javax.swing.JLabel carta7j;
    private javax.swing.JLabel carta8j;
    private javax.swing.JLabel carta9j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel player_panel;
    private javax.swing.JLabel resulttext;
    // End of variables declaration//GEN-END:variables
}
