package es.jimenezfrontend.gui;

import es.jimenezfrontend.objects.Game;
import java.awt.Component;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
* DAM, IES Ribera de Castilla
* @author José Antonio
*/
public class PlayerForm extends javax.swing.JFrame {

    Component[] components;
    int card_number = 0;
    String thepath = "/es/jimenezfrontend/images/";
    URL url;
    Game myGame = Game.getInstance();
    double value = 0.0;
    int pnumber;
    boolean is_paused = false;

    public PlayerForm(String name, int player_number) {

	initComponents();
	pnumber = player_number;
	final TitledBorder tb = BorderFactory.createTitledBorder(name);
	player_panel.setBorder(tb);
	player_panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        new_game_button = new javax.swing.JButton();
        get_card_button = new javax.swing.JButton();
        player_panel = new javax.swing.JPanel();
        carta1j = new javax.swing.JLabel();
        carta2j = new javax.swing.JLabel();
        carta3j = new javax.swing.JLabel();
        carta4j = new javax.swing.JLabel();
        carta5j = new javax.swing.JLabel();
        carta6j = new javax.swing.JLabel();
        carta7j = new javax.swing.JLabel();
        carta8j = new javax.swing.JLabel();
        carta9j = new javax.swing.JLabel();
        carta10j = new javax.swing.JLabel();
        resulttext = new javax.swing.JLabel();
        stick_button = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        new_game_button.setText("Nueva Partida");
        new_game_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_game_event(evt);
            }
        });

        get_card_button.setText("Sacar Carta");
        get_card_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_card_event(evt);
            }
        });

        player_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 1"));
        player_panel.setLayout(new java.awt.GridLayout(1, 0));
        player_panel.add(carta1j);
        player_panel.add(carta2j);
        player_panel.add(carta3j);
        player_panel.add(carta4j);
        player_panel.add(carta5j);
        player_panel.add(carta6j);
        player_panel.add(carta7j);
        player_panel.add(carta8j);
        player_panel.add(carta9j);
        player_panel.add(carta10j);

        stick_button.setText("Plantarse");
        stick_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stick_event(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                            .addComponent(get_card_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(new_game_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(resulttext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stick_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(player_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(get_card_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stick_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resulttext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(new_game_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:

    try {
	components = this.player_panel.getComponents();

    }
    catch (Exception e) {
	System.out.println(e.toString());
    }


}//GEN-LAST:event_formWindowOpened

private void new_game_event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_game_event
    int result = JOptionPane.showOptionDialog(null,
	    "¿Seguro que deseas terminar la partida?",
	    "Fin del juego",
	    JOptionPane.YES_NO_CANCEL_OPTION,
	    JOptionPane.INFORMATION_MESSAGE,
	    null,
	    new String[]{
		"Si, salir", "No, continuar", "Reiniciar",}, // this is the array
	    "default");

    if (result == JOptionPane.CANCEL_OPTION) {
	System.out.println("reiniciando");
	myGame.exitGame();

    }
    else if (result == JOptionPane.YES_OPTION) {
	System.out.println("saliendo");
	System.exit(0);
    }
}//GEN-LAST:event_new_game_event

private void get_card_event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_card_event
    pause_game();
    String[] response = myGame.Deal();
    //System.out.println(thepath + response[0]);
    value = value + Double.valueOf(response[1]);
    //System.out.println(response[2]);
    System.out.println(value);
    url = this.getClass().getResource(thepath + response[0]);
    ImageIcon icon = new ImageIcon(url);
    ((JLabel) components[card_number]).setIcon(icon);
    ((JLabel) components[card_number]).setVisible(true);
    card_number++;
    if (response[2].equals("true")) {
	myGame.MakeIADeal();
    }
    if (value >= 7.5) {
	stick_event(evt);
    }

}//GEN-LAST:event_get_card_event

    public void resume_game() {
	get_card_button.setEnabled(true);
	stick_button.setEnabled(true);
    }

    private void pause_game() {
	get_card_button.setEnabled(false);
	stick_button.setEnabled(false);
    }
    private void stick_event(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stick_event
    {//GEN-HEADEREND:event_stick_event
	pause_game();
	String[] response2 = myGame.stopThread(pnumber, value);
	resulttext.setText(response2[0]);
    }//GEN-LAST:event_stick_event


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carta10j;
    private javax.swing.JLabel carta1j;
    private javax.swing.JLabel carta2j;
    private javax.swing.JLabel carta3j;
    private javax.swing.JLabel carta4j;
    private javax.swing.JLabel carta5j;
    private javax.swing.JLabel carta6j;
    private javax.swing.JLabel carta7j;
    private javax.swing.JLabel carta8j;
    private javax.swing.JLabel carta9j;
    private javax.swing.JButton get_card_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton new_game_button;
    private javax.swing.JPanel player_panel;
    private javax.swing.JLabel resulttext;
    private javax.swing.JButton stick_button;
    // End of variables declaration//GEN-END:variables
}
