/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerForm.java
 *
 * Created on 23-feb-2012, 13:03:15
 */
package es.jimenezfrontend.gui;

import es.jimenezfrontend.Game;
import java.awt.Component;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author rocio
 */
public class PlayerForm extends javax.swing.JFrame {

    Component[] components;
    int card_number = 0;
    String thepath = "/es/jimenezfrontend/images/";
    URL url;
    Game myGame = Game.getInstance();
    double value = 0.0;
    int pnumber;
    boolean is_paused = false;

    public PlayerForm(String name, int player_number) {

	initComponents();
	pnumber = player_number;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNueva_Partida = new javax.swing.JButton();
        btnSacar_Carta = new javax.swing.JButton();
        panel_jugador1 = new javax.swing.JPanel();
        carta1j = new javax.swing.JLabel();
        carta2j = new javax.swing.JLabel();
        carta3j = new javax.swing.JLabel();
        carta4j = new javax.swing.JLabel();
        carta5j = new javax.swing.JLabel();
        carta6j = new javax.swing.JLabel();
        carta7j = new javax.swing.JLabel();
        carta8j = new javax.swing.JLabel();
        carta9j = new javax.swing.JLabel();
        carta10j = new javax.swing.JLabel();
        resulttext = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnNueva_Partida.setText("Nueva Partida");
        btnNueva_Partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueva_PartidaActionPerformed(evt);
            }
        });

        btnSacar_Carta.setText("Sacar Carta");
        btnSacar_Carta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacar_CartaActionPerformed(evt);
            }
        });

        panel_jugador1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 1"));
        panel_jugador1.setLayout(new java.awt.GridLayout(1, 0));
        panel_jugador1.add(carta1j);
        panel_jugador1.add(carta2j);
        panel_jugador1.add(carta3j);
        panel_jugador1.add(carta4j);
        panel_jugador1.add(carta5j);
        panel_jugador1.add(carta6j);
        panel_jugador1.add(carta7j);
        panel_jugador1.add(carta8j);
        panel_jugador1.add(carta9j);
        panel_jugador1.add(carta10j);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_jugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                            .addComponent(btnSacar_Carta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(resulttext, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNueva_Partida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSacar_Carta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnNueva_Partida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(resulttext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:

    try {
	components = this.panel_jugador1.getComponents();

    }
    catch (Exception e) {
	System.out.println(e.toString());
    }


}//GEN-LAST:event_formWindowOpened

private void btnNueva_PartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueva_PartidaActionPerformed

}//GEN-LAST:event_btnNueva_PartidaActionPerformed

private void btnSacar_CartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacar_CartaActionPerformed
// TODO add your handling code here:
    String[] response = myGame.Deal();
    System.out.println(thepath + response[0]);
    value = value+Double.valueOf(response[1]);
    System.out.println(value);
    url = this.getClass().getResource(thepath + response[0]);
    ImageIcon icon = new ImageIcon(url);
    ((JLabel) components[card_number]).setIcon(icon);
    ((JLabel) components[card_number]).setVisible(true);
    card_number++;
	try {
	    Thread.sleep(400);
	}
	catch (InterruptedException ex) {
	    Logger.getLogger(PlayerForm.class.getName()).log(Level.SEVERE, null, ex);
	}
    
    if (value >= 7.5) {
	btnSacar_Carta.setEnabled(false);
	String[] response2 = myGame.stopThread(pnumber,value);
	resulttext.setText(response2[0]);
    }
    /*synchronized (this){
	try {
	    this.wait();
	    is_paused = true;
	    while (is_paused){
		is_paused = myGame.exitpause();
		if (is_paused == false){
		    this.notifyAll();
		}
	    }
	}
	catch (InterruptedException ex) {
	    Logger.getLogger(PlayerForm.class.getName()).log(Level.SEVERE, null, ex);
	}
    }*/
}//GEN-LAST:event_btnSacar_CartaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNueva_Partida;
    private javax.swing.JButton btnSacar_Carta;
    private javax.swing.JLabel carta10j;
    private javax.swing.JLabel carta1j;
    private javax.swing.JLabel carta2j;
    private javax.swing.JLabel carta3j;
    private javax.swing.JLabel carta4j;
    private javax.swing.JLabel carta5j;
    private javax.swing.JLabel carta6j;
    private javax.swing.JLabel carta7j;
    private javax.swing.JLabel carta8j;
    private javax.swing.JLabel carta9j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_jugador1;
    private javax.swing.JLabel resulttext;
    // End of variables declaration//GEN-END:variables
}
